"""capaign freq err

Revision ID: 04b31b1df725
Revises: 5817cb7ce91f
Create Date: 2025-04-23 17:45:40.480919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b31b1df725'
down_revision = '5817cb7ce91f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###
