"""tried fixing default problem

Revision ID: 25afb56a85b6
Revises: 6a5d1d486ac8
Create Date: 2025-04-08 12:29:55.407123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25afb56a85b6'
down_revision = '6a5d1d486ac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
