"""test

Revision ID: 4bf30d7a7aeb
Revises: f8ee171b772e
Create Date: 2025-03-24 17:15:00.156241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf30d7a7aeb'
down_revision = 'f8ee171b772e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gym_settings', sa.Column('gym_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'gym_settings', 'gyms', ['gym_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gym_settings', type_='foreignkey')
    op.drop_column('gym_settings', 'gym_id')
    # ### end Alembic commands ###
