"""add all the tables

Revision ID: 553b8b8906f8
Revises: 
Create Date: 2025-03-20 06:52:24.008074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553b8b8906f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
