"""made capaigns better

Revision ID: 5817cb7ce91f
Revises: 8980199aa42d
Create Date: 2025-04-21 21:23:04.762362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5817cb7ce91f'
down_revision = '8980199aa42d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_constraint('follow_up_campaigns_lead_id_fkey', 'follow_up_campaigns', type_='foreignkey')
    op.drop_column('follow_up_campaigns', 'lead_id')
    op.add_column('leads', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'leads', 'follow_up_campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'campaign_id')
    op.add_column('follow_up_campaigns', sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('follow_up_campaigns_lead_id_fkey', 'follow_up_campaigns', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###
