"""Reset external_call_id to string type

Revision ID: 68b1b03fdb50
Revises: 03ee265cc61d
Create Date: 2025-03-30 14:16:18.452366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b1b03fdb50'
down_revision = '03ee265cc61d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
