"""update user ids to UUID type

Revision ID: 6a5d1d486ac8
Revises: 834c466287a3
Create Date: 2025-04-01 14:36:51.704682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5d1d486ac8'
down_revision = '834c466287a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
