"""tried to fix campaign id

Revision ID: 834c466287a3
Revises: 2a0e4474110d
Create Date: 2025-03-27 10:14:19.949109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834c466287a3'
down_revision = '2a0e4474110d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_logs', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_logs', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
