"""made capaigns better

Revision ID: 8980199aa42d
Revises: 25afb56a85b6
Create Date: 2025-04-21 20:53:19.540039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8980199aa42d'
down_revision = '25afb56a85b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('follow_up_campaigns', sa.Column('call_count', sa.Integer(), nullable=True))
    
    # Update existing rows to set call_count to 0
    op.execute("UPDATE follow_up_campaigns SET call_count = 0 WHERE call_count IS NULL")
    
    # Then make it not nullable
    op.alter_column('follow_up_campaigns', 'call_count', nullable=False, server_default='0')
    
    # Add metrics column
    op.add_column('follow_up_campaigns', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_up_campaigns', 'metrics')
    op.drop_column('follow_up_campaigns', 'call_count')
    # ### end Alembic commands ###
