name: Deploy on PR Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make deploy script executable and run it
        run: |
          chmod +x /Users/home/reps-ai-backend/reps-ai-dashboard-backend/update_and_redeploy.sh
          /Users/home/reps-ai-backend/reps-ai-dashboard-backend/update_and_redeploy.sh
