name: Deploy to Mac mini

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Webhook on Mac mini
        run: |
          curl -X POST https://deploy-github.rthulabs.com/deploy \
            -H "X-Deploy-Token: ${{ secrets.DEPLOY_TOKEN }}"
