name: Deploy to Mac mini

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MACMINI_SSH_KEY }}" > ~/.ssh/macmini_deploy_key
          chmod 600 ~/.ssh/macmini_deploy_key

      - name: Connect and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/macmini_deploy_key home@ssh.rthulabs.com "bash ~/scripts/deploy.sh"
